### ISSUE TITLE
Ecig wiring

### ISSUE THREAD

**Issue by Tom-Neverwinter** [CountDeMonet/ArduinoProtonPack#16]
I am going to go out on a limb and assume this is the circuit for the ecig version or close enough.
https://www.gbfans.com/forum/viewtopic.php?t=36943&start=210

**Comment by CountDeMonet** [comment]
Since the code supports relays yes, anything after the relay is good as it is a completely different circuit. The mighty part is replaced by the arduino pin 13 which goes to the en of the relay in that diagram.
