### ISSUE TITLE
Wand board with bar graph

### ISSUE THREAD

**Issue by dougbevan** [CountDeMonet/ArduinoProtonPack#24]
Great project, in many ways better than the pre-made kits, and tweak-able!

Did you happen to do a wand io board that includes the bar graph?  I'm putting together the whole project including bar graph, and it would be great to have a board that includes it.

**Comment by CountDeMonet** [comment]
Glad you are finding it useful. I never did get around to ordering the boards and finishing that. I ran out of time and ended up wiring them up manually with proto boards. It would be a fun project to design that but I didn't have time. 

These are the only images I have of the bargraph proto board I built. Worked well. 
![bargraph_front](https://user-images.githubusercontent.com/10222510/146601011-85347fa1-96dd-4603-80dc-4f13a62e8f21.jpg)
![bargraph_rear](https://user-images.githubusercontent.com/10222510/146601014-fc774e1b-9a59-4ac2-b70d-d9c1365f6bd3.jpg)

**Comment by dougbevan** [comment]
Appreciate the images and response.  Yes, it's a great project and a fantastic contribution to the community.

I'm fine with programming but have never tried my hand at Eagle.  I did order the boards you designed to give them a try, but I will try extending the wand.io board to include signals/power for the bar graph.
