### ISSUE TITLE
Using Pixel Jewels instead of Individual neopixels

### ISSUE THREAD

**Issue by ghostbuster84** [CountDeMonet/ArduinoProtonPack#29]
Im using the spirit minimal code because these lights are going in a pack thats on display. I bought the jewels since thats what i used in the full pack. Is there an easy way to configure those to work in place of the individual pixels?

**Comment by ghostbuster84** [comment]
After some reading looking at the code, I was able to set each one as a strand of 7 LEDS and it works perfect now.

**Comment by CountDeMonet** [comment]
Glad you figured it out. I tried to make the code easy to deal with different light combinations. Looks like it works :)
