### ISSUE TITLE
Cant compile with bar graph

### ISSUE THREAD

**Issue by G1Soundwave** [CountDeMonet/ArduinoProtonPack#4]
Ive been fighting with this a bit now, the code without bar graph works great, but with bargraph, it stops compiling and gives this error- "'shutdown_leds' was not declared in this scope" I would try to fix it myself, but to be honest, I know almost nothing about coding. But I will say, even without the bargraph, excellent job on it!

**Comment by CountDeMonet** [comment]
That is really odd. The code compiles for me. I would make sure you have pulled the latest code from the repository and retry compiling. The full code is here

https://github.com/CountDeMonet/ArduinoProtonPack/blob/master/Arduino/Neutrino_Wand_With_Graph/Neutrino_Wand_With_Graph.ino

That function it is complaining about is down at line 1102 and should look like this


```
void shutdown_leds() {
  // reset the sequence
  seq_1_current = 1;
  fireSequenceNum = 1;

  // shut all led's off
  for (int i = 1; i <= 15; i++) {
    switch_graph_led(i, LOW);
  }
}
```

**Comment by acfq48** [comment]
For anyone interested:  Spirit Halloween is releasing a ghost trap and PKE
meter among a few other new Ghostbuster items.  They're running for $50 and
$35 respectively and look pretty good.  I'll be working on a foot pedal mod
for the trap as soon as I get it but if anyone beats me to it, be sure to
post.

https://www.spirithalloween.com/product/ghostbuster-ghost-trap-ghostbusters/164228.uts?keyword=ghost
trap&thumbnailIndex=1&Search=Find+It

Enjoy!

**Comment by G1Soundwave** [comment]
Not sure what happened, but seems it was missing those sections in the code. Redownloaded it, and working fine. Dont know why I didnt think to try that. Thanks alot.
