### ISSUE TITLE
help

### ISSUE THREAD

**Issue by BSKStudio** [CountDeMonet/ArduinoProtonPack#6]
This is something probably that I'm doing wrong.  Im having a issue when Im importing the zip file into my library?  its not allowing the queue array to and other files to import?

**Comment by CountDeMonet** [comment]
Make sure you install the libraries to the library folder for the ide

https://www.arduino.cc/en/guide/libraries#toc3

**Comment by BSKStudio** [comment]
Awesome thank you!

**Comment by Autocado** [comment]
how do I uploads the code and sound

**Comment by CountDeMonet** [comment]
@Autocado you are going to want to review this page on getting started with the arduino

https://www.arduino.cc/en/main/howto

and this page on uploading files to the audiofx board

https://learn.adafruit.com/adafruit-audio-fx-sound-board/copying-audio-files
